version: "3"

services:
    
    dbserver:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: 12345678
            MYSQL_DATABASE: test_db
            MYSQL_USER: devuser
            MYSQL_PASSWORD: devpass
        ports:
            - "3306:3306"
    webserver:
        image: php-apache-kk
        container_name: my-apache-php-kk
        depends_on:
            - dbserver
        volumes:
            - ./:/var/www/html/
        ports:
            - "80:80"
        stdin_open: true
        tty: true
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: 'my-myadmin'
        depends_on:
            - dbserver
        environment:
            PMA_HOST: dbserver
            PMA_PORT: 3306
        ports:
            - '8080:80'
